# Generated by Django 5.2.5 on 2025-11-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rt', 'Revision técnica'), ('pc', 'Permiso de circulación'), ('so', 'Soap')], max_length=2)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('puntaje_validacion', models.PositiveIntegerField(default=0)),
                ('detalles_validacion', models.JSONField(default=dict)),
            ],
        ),
    ]
