# Generated by Django 5.2.5 on 2025-11-08 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos_vehiculo', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentovehicular',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentovehicular',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='documentovehicular',
            index=models.Index(fields=['user', 'vehiculo', 'tipo', 'activo'], name='documentos__user_id_f75473_idx'),
        ),
    ]
