# Generated by Django 5.2.5 on 2025-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_vehiculo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentovehicular',
            name='archivo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentovehicular',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
