# Generated by Django 5.2.5 on 2025-11-19 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('documento', 'Documento por vencer / subido'), ('mantenimiento', 'Mantenimiento registrado'), ('qr', 'QR generado / vencido'), ('sistema', 'Notificación del sistema')], default='sistema', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('enviada_email', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
