# Generated by Django 5.2.5 on 2025-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalizacion',
            name='observacion',
        ),
        migrations.AddField(
            model_name='fiscalizacion',
            name='advertencias',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='fiscalizacion',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
