# Generated by Django 5.2.5 on 2025-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_sharedaccess_alter_sharedaccesslog_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccess',
            name='receptor_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sharedaccess',
            name='receptor_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
