# Generated by Django 5.2.5 on 2025-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_sharedaccess_receptor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccesslog',
            name='is_prestamo',
            field=models.BooleanField(default=False),
        ),
    ]
