# Generated by Django 5.2.5 on 2025-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0004_sharedaccesslog_is_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccess',
            name='qr_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
