# Generated by Django 5.2.5 on 2025-11-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('tipo_servicio', models.CharField(choices=[('aceite', 'Cambio de aceite'), ('frenos', 'Frenos'), ('motor', 'Motor'), ('electrico', 'Eléctrico'), ('completo', 'Servicio completo')], default='completo', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='TallerFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.taller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'taller')},
            },
        ),
    ]
